export const actionType = {
  BIRD_FLY: "BIRD_FLY",
  BIRD_FALL: "BIRD_FALL",

  PIPE_MOVING: "PIPE_MOVING",
  PIPE_GENERATE: "PIPE_GENERATE",

  GAME_START: "GAME_START",
  GAME_OVER: "GAME_OVER",
};
